version: '3.4'
services:

  alternat:
    container_name: alternat
    image: keplerlab/alternat:0.1.5
    ports:
    - "8080:8080"
    volumes:
       - .:/home/myuser/alternat
       - /home/myuser/alternat/alternat/collection/apify/node_modules/
    environment:
      - SERVER_INTERFACE=0.0.0.0
